### ISSUE TITLE
Nuevo Concepto: Pseudovía

### ISSUE THREAD

**Issue by paoespinozarias** [opencitydata/urbanismo-infraestructuras-callejero#15]
Teniendo en cuenta la definición de _Pseudovías_ del fichero de _Relación de Pseudovías_, incluida en el [diseño de ficheros de intercambio de información INE-Ayuntamientos](https://idapadron.ine.es/repositorio/DisReg/disregok.PDF), es necesario incluir este concepto en este vocabulario, ya que se considera que son _"aquellas unidades que no se encuadran en el concepto de Unidad Poblacional ni de Vía  (Barrios,  Urbanizaciones,etc.),  que  sustituyen  a  la  Vía  en  el  caso  de  que  no exista o que la complementan en caso contrario."_

Por lo tanto, será necesario modificar el comentario del concepto _Via_ de este vocabulario pues actualmente menciona que incluye la pseudovía.

**Comment by paoespinozarias** [comment]
Al considerar este nuevo concepto, es necesario tener en cuenta que la pseudovía también considera tramos con su respectiva numeración de inicio y fin. 

Por lo tanto, una opción podría ser renombrar el concepto _TramoVia_ por _Tramo_ y redefinirlo de tal forma que se pueda representar cualquier tramo ya sea de vía o pseudovía.  Otra opción podría ser definir uno nuevo (_TramoPseudovía_) para representarlo.

En todo caso se tendría que considerar lo que viene descrito en el [callejero del INE](https://www.ine.es/ss/Satellite?L=0&c=Page&cid=1254735624326&p=1254735624326&pagename=ProductosYServicios%2FPYSLayout) y en el fichero de [Relación de Tramos](https://idapadron.ine.es/repositorio/DisReg/disregok.PDF). En este último también se contempla el concepto de _Unidad Poblacional_ que a efectos censales es considerado por el INE. ([ejemplo de Unidad Poblacional](http://www.ine.es/nomen2/Ayuda.do))

**Comment by ocorcho** [comment]
Se ha actualizado la clase Vía para eliminar la referencia a pseudovía y se ha creado el concepto PseudoVía como subclase de Vía.
También se ha renombrado la clase TramoVía por Tramo
