### ISSUE TITLE
Propiedad escjr:portal

### ISSUE THREAD

**Issue by jcballesteros** [opencitydata/urbanismo-infraestructuras-callejero#16]
Actualmente la clase Portal solo puede ser relacionada con otra entidad a través de la propiedad "contienePortal", necesitamos una propiedad "portal" para poder enlazar entidades con la clase "Portal". Ejemplo: indicar que un equipamiento municipal se encuentra en un determinado portal.

**Comment by ocorcho** [comment]
Resuelto en commit bff1a372551f09f0758ea576118bb0d43d87eff1
Esta versión de la ontología, junto con su documentación actualizada, será publicada online a posteriori
