### ISSUE TITLE
Ejemplo SKOS 

### ISSUE THREAD

**Issue by mariapoveda** [opencitydata/urbanismo-infraestructuras-callejero#4]
En el ejemplo de http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero.html#ontDescription aparece la siguiente URI como tipo via http://vocab.linkeddata.es/datosabiertos/kos/urbanismo-infraestructuras/tipo-via/CL 

Esta URI da un error 404.

¿Debería ser http://vocab.linkeddata.es/page/datosabiertos/kos/urbanismo-infraestructuras/tipo-via/CALLE ?

**Comment by ocorcho** [comment]
Realmente se trataba de http://vocab.linkeddata.es/page/datosabiertos/kos/urbanismo-infraestructuras/tipo-via/CALLE 
Se modifica en la documentación, que será publicada posteriormente, en el commit 7baf1ea8be620b33c69d6aa5de7573e8cbb49e36
