### ISSUE TITLE
Problema URI

### ISSUE THREAD

**Issue by jperez4** [opencitydata/urbanismo-infraestructuras-callejero#7]
La siguiente línea de la ontología contiene una URI invalida

`<dcterms:replaces rdf:resource="http://vocab.linkeddata.es/datosabiertos/def/urbanismo-infraestructuras/callejero_20140321"/`

> **404 Not Found**

**Comment by ocorcho** [comment]
Resuelto en commit bff1a372551f09f0758ea576118bb0d43d87eff1
